name: Daily Music Bot

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  send-song:
    runs-on: ubuntu-latest

    steps:
      - name: Run bot
        uses: actions/checkout@v4

      - name: Send random song
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python daily.py